"""Constants used across the vap_tqip preprocessing pipeline."""

from __future__ import annotations

AIS_COLUMNS = [
    "mxaisbr_HeadNeck",
    "mxaisbr_Face",
    "mxaisbr_Chest",
    "mxaisbr_Abdomen",
    "mxaisbr_Extremities",
]

REQUIRED_COLUMNS = [
    "YODISCH",
    "AGEyears",
    "riss",
    "ETHNICITY",
    "SUPPLEMENTALOXYGEN",
    "RESPIRATORYASSISTANCE",
    "WITHDRAWALLST",
    "PREHOSPITALCARDIACARREST",
    "HC_RESPIRATORY",
    "HC_VAPNEUMONIA",
    "HC_PNEUMONIA",
    "TEMPERATURE",
    "SEX",
    "HMRRHGCTRLSURGTYPE",
    "VERIFICATIONLEVEL",
    *AIS_COLUMNS,
]

OHE_RENAME_MAP = {
    "SEX_1.0": "sex_male",
    "SEX_2.0": "sex_female",
    "SEX_3.0": "sex_non-binary",
    "HMRRHGCTRLSURGTYPE_1.0": "surg_none",
    "HMRRHGCTRLSURGTYPE_2.0": "surg_laparotomy",
    "HMRRHGCTRLSURGTYPE_3.0": "surg_thoracotomy",
    "HMRRHGCTRLSURGTYPE_4.0": "surg_sternotomy",
    "HMRRHGCTRLSURGTYPE_5.0": "surg_extremity",
    "HMRRHGCTRLSURGTYPE_6.0": "surg_neck",
    "HMRRHGCTRLSURGTYPE_7.0": "surg_amputation",
    "HMRRHGCTRLSURGTYPE_8.0": "surg_skin_softtissue",
    "HMRRHGCTRLSURGTYPE_9.0": "surg_pelvic_packing",
}

RAW_ENCODED_COLUMNS_TO_DROP = ("SEX", "HMRRHGCTRLSURGTYPE", "VERIFICATIONLEVEL")

CAT_FEATURES = [
    "HC_VAPNEUMONIA",
    "WHITE",
    "BLACK",
    "ETHNICITY",
    "PACIFICISLANDER",
    "AMERICANINDIAN",
    "ASIAN",
    "RACEOTHER",
    "WITHDRAWALLST",
    "INTERFACILITYTRANSFER",
    "RESPIRATORYASSISTANCE",
    "SUPPLEMENTALOXYGEN",
    "PREHOSPITALCARDIACARREST",
    "VERIFICATIONLEVEL",
    "Mortality",
    "CC_CHEMO",
    "CC_CIRRHOSIS",
    "CC_COPD",
    "CC_CVA",
    "CC_DIABETES",
    "CC_DISCANCER",
    "CC_FUNCTIONAL",
    "CC_CHF",
    "CC_RENAL",
    "CC_SMOKING",
    "ICP_Monitor",
    "sex_male",
    "sex_female",
    "sex_non-binary",
    "surg_none",
    "surg_laparotomy",
    "surg_thoracotomy",
    "surg_sternotomy",
    "surg_extremity",
    "surg_neck",
    "surg_amputation",
    "surg_skin_softtissue",
    "surg_pelvic_packing",
    "inj_HeadNeck",
    "inj_Face",
    "inj_Chest",
    "inj_Abdomen",
    "inj_Extremities",
    "L1",
    "L2",
    "L3",
]

NUM_FEATURES = [
    "TOTALVENTDAYS",
    "AGEyears",
    "HMRRHGCTRLSURGMins",
    "HMRRHGCTRLSURGDays",
    "WITHDRAWALLSTMins",
    "WITHDRAWALLSTDays",
    "TOTALICULOS",
    "Hospital_LOS_Hr",
    "Hospital_LOS_Days",
    "riss",
    "mxaisbr_HeadNeck",
    "mxaisbr_Face",
    "mxaisbr_Chest",
    "mxaisbr_Abdomen",
    "mxaisbr_Extremities",
    "SBP",
    "PULSERATE",
    "TEMPERATURE",
    "RESPIRATORYRATE",
    "PULSEOXIMETRY",
    "PRBC_4",
    "FFP_4",
    "PLT_4",
    "WB",
    "WB_time_mins",
]
